### ISSUE TITLE
500 Internal Server Error on global settings

### ISSUE THREAD

**Issue by atopcu** [akiko-pusu/redmine_banner#54] opened 2015-05-15 07:13 UTC
Hello akiko-pusu,
I'm using your plugin since long time. There is 500 Internal Server Error now. however, this conflict is in global settings only, not the project settings.

This problem started after installing an other plugin ( https://github.com/zaneli/akayagi ). I want to use both of these plugins. I am updating global settings with direct-accessing to DB now.

log:
Started GET "/settings/plugin/redmine_banner" for x.x.x.x at 2015-05-15 09:54:34 +0300
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"redmine_banner"}
  Rendered plugins/redmine_banner/app/views/settings/_redmine_banner.html.erb (29.7ms)
  Rendered plugins/redmine_banner/app/views/settings/plugin.html.erb within layouts/admin (51.4ms)
Completed 500 Internal Server Error in 121.2ms

ActionView::Template::Error (undefined method `strftime' for nil:NilClass):
    70: <div id="banner_timer_setting" style="display: <%= @settings['use_timer'] == 'true' ? 'block' : 'none' %>">
    71:   <p>
    72:     <%=content_tag(:label, l(:label_start_datetime))%>
    73:     <%= text_field_tag 'settings[start_ymd]', @start_datetime.strftime("%Y-%m-%d"), :size => 10 %>
    74:     <%= select_hour @start_datetime, :prefix => 'settings', :field_name => 'start_hour',
    75:       :time_separator => ':', :include_seconds => false %>:
    76:     <%= select_minute @start_datetime, :prefix => 'settings', :field_name => 'start_min', :time_separator => ':', :include_seconds => false %>
  plugins/redmine_banner/app/views/settings/_redmine_banner.html.erb:73:in `_plugins_redmine_banner_app_views_settings__redmine_banner_html_erb___4012071094739498116_70150482271060'

Environment:
  Redmine version                2.6.4.stable.14229
  Ruby version                   2.0.0-p481 (2014-05-08) [x86_64-linux]
  Rails version                  3.2.21
  Environment                    production
  Database adapter               Mysql2

**Comment by akiko-pusu** [comment] 2015-05-15 10:24
Hi, @atopcu. Thank you for your using my plugin.
Could you please tell me the version of Banner Plugin and Akayagi plugin.
And also I'm going to test if some problem is shown or not in my env.

**Comment by atopcu** [comment] 2015-05-15 11:20
Thanks for quick reply. Versions:
akayagi => 0.0.2
redmine_banner => 0.1.0

I know, there is 0.1.1 version of redmine_banner. I was tried it, but error was same on it

Regards..

**Comment by akiko-pusu** [comment] 2015-05-24 01:02
@atopcu, sorry for the late reply and inconvenient for you.
I could reproduce the problem when install both plugin.

Maybe the problem is caused by using the same name for patch file against settings controller.

Here is workaround.
Please modify init.rb and akayagi plugin like this. 

```
diff --git a/app/helpers/method_chain/settings_controller_patch.rb b/app/helpers/method_chain/settings_controller_patch.rb
index 327f554..3e31bfb 100644
--- a/app/helpers/method_chain/settings_controller_patch.rb
+++ b/app/helpers/method_chain/settings_controller_patch.rb
@@ -21,4 +21,4 @@ module InstanceMethods
   end
 end
 
-SettingsController::send(:include, SettingsControllerPatch)
+#SettingsController::send(:include, SettingsControllerPatch)
diff --git a/init.rb b/init.rb
index 4350315..8e7b523 100644
--- a/init.rb
+++ b/init.rb
@@ -16,6 +16,9 @@ Redmine::Plugin.register :akayagi do
 end
 
 Rails.configuration.to_prepare do
+  unless SettingsController.included_modules.include?(SettingsControllerPatch)
+    SettingsController.send(:include, SettingsControllerPatch)
+  end
   unless ProjectsHelper::included_modules.include? ProjectsHelperPatch
     ProjectsHelper::send(:include, ProjectsHelperPatch)
   end
``` 

Anyway, I'm going to modify my code not to use SettingsController patch to prevent conflict.
(Also planning to generate new table for global banner instead of settings table.)

Please wait for a while.

**Comment by akiko-pusu** [comment] 2015-11-24 03:26
@atopcu , Sorry for my delayed reply.
I've renamed my patch file's name to prevent conflict akayagi plugin.
This commit was merged into master branch :)

But personally I think this is just a workaround and if some other plugin which has the same name patch file, this problem will be happened.

**Closed by akiko-pusu** 2015-11-24 03:26 UTC
Labels: feature, task
